name: coverage CI
on:
  push:
    branches: [main]
    paths:
      - "packages/**/*.ts"
      - "vitest.config.mts"
      - ".github/workflows/coverage.yml"

permissions:
  contents: read
  id-token: write # IMPORTANT

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@9b5745cdf0a2e8c2620f0746130f809adb911c19 # v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install

      - name: Playwrite install
        run: pnpm exec playwright install

      - name: Run tests
        run: pnpm run test

      - name: Run and publish code coverage
        uses: qltysh/qlty-action/coverage@a19242102d17e497f437d7466aa01b528537e899 # v2.2.0
        with:
          oidc: true
          files: coverage/lcov.info
