name: Module Common CI
on:
  workflow_call:
    inputs:
      package-path:
        required: true
        type: string

env:
  # Setting an environment variable with the value of a configuration variable
  PUBLISH_BRANCH: "refs/heads/main"
  PACKAGE_NAME: "unknown"
  PACKAGE_VERSION: "unknown"
  NPM_VERSION: "unknown"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dcarbone/install-jq-action@v2
      - uses: actions/checkout@v4

      - name: Identify project environment variables
        working-directory: ${{ inputs.package-path }}
        run: |
          echo "PACKAGE_NAME=$(cat package.json | jq -r .name)" | tee -a $GITHUB_ENV
          echo "PACKAGE_VERSION=$(cat package.json | jq -r .version)" | tee -a $GITHUB_ENV

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: Get current npmjs version for ${{env.PACKAGE_NAME}}
        run: |
          echo "NPM_VERSION=$(curl -s https://registry.npmjs.org/${{ env.PACKAGE_NAME }} | jq -r '."dist-tags".latest')" | tee -a $GITHUB_ENV

      - name: Install workspace deps
        run: pnpm install

      - name: Playwrite install
        run: pnpm exec playwright install

      - name: Build
        run: pnpm run build

      - name: Validate
        run: pnpm run validate

      - name: Test
        run: pnpm run test

      - name: Lint
        run: pnpm run lint

      - name: Publish ${{env.PACKAGE_NAME}} ${{env.PACKAGE_VERSION}}
        working-directory: ${{ inputs.package-path }}
        if: |
          github.ref == env.PUBLISH_BRANCH &&
          env.PACKAGE_VERSION != env.NPM_VERSION
        run: npm publish --access public
